[project]
name = "mcp-explorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "pytz>=2025.2",
    "yacs>=0.1.8",
]
