[project]
name = "timeserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pytz>=2025.2",
    "starlette>=0.46.2",
]
